name: smart_textfield
description: "TextField that can extract relevant information from the raw text input."
version: 0.0.1
repository: https://github.com/Yogi-7y/Project-Y/tree/main/packages/smart_textfield

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.16.9"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter
  flutter_portal: ^1.1.4
  meta: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints_y:
    path: ../lints_y

flutter:
